import {LANDMARKS,BIOMES,LOOP_LENGTH,routeSample,biomeWeather,riverZ,waterExists} from './expedition.mjs';
import {RiverView} from './river-view.mjs';
import {CoastalAtmosphere} from './coastal-atmosphere.mjs';
import {VehicleSnow} from './vehicle-snow.mjs';
import {VehicleLights} from './vehicle-lights.mjs';
import {WeatherView} from './weather-view.mjs';
import {createWeatherUI} from './weather-ui.mjs';
import {createDriveIntro} from './drive-intro.mjs';
import {PowerAntenna} from './antenna.mjs';
import {createMusic} from './music.mjs';
import {createKeyboardControls} from './keyboard.mjs';
import {createSound} from './sound.mjs';
import * as THREE from 'three/webgpu';
import {positionLocal,mix,color,smoothstep,pass,renderOutput} from 'three/tsl';
import {fxaa} from 'three/addons/tsl/display/FXAANode.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {Recovery} from './recovery.mjs';
import {RecoveryView} from './recovery-view.mjs';
import {RANGES} from './drivetrain.mjs';
import {DrivePhysics,wheelLayout} from './physics.mjs';
import {SandField,baseHeight,shore,smooth,clamp,surfaceAt} from './terrain.mjs';
import {TerrainView} from './terrain-view.mjs';
import {Ocean} from './ocean.mjs';
import {WaypointRoute,WAYPOINT_COUNT} from './waypoints.mjs';
import {WaypointView} from './waypoint-view.mjs';
import {BeachObstacles} from './obstacles.mjs';
import {SunsetClouds} from './clouds.mjs';
import {BeachLife} from './beach-life.mjs';
import {SurfaceEffects} from './surface-effects.mjs';
const previewMode=new URLSearchParams(location.search).get('preview')==='1';
if(previewMode)document.documentElement.classList.add('preview-mode');
let previewActive=false;
const $=id=>document.getElementById(id),canvas=$('view'),mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(parent!==window)$('exit').hidden=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,1500),field=new SandField();
let renderer,scenePass,renderPipeline,physics,terrain,obstacles,truck,antenna,vehicleLights,vehicleSnow,recovery,recoveryView,wheels=[],paused=false,loaded=false,dead=false,last=0,accumulator=0,elapsed=0,frameCount=0,cruise=false,started=false,quipUntil=0,camYaw=0,recoveryCamera=0,lastStamp=[],waterCenter=Infinity,aimHeight=null;
const keys=new Set(),touch={left:false,right:false,gas:false,brake:false},temp=new THREE.Vector3(),dummy=new THREE.Object3D(),q=new THREE.Quaternion();
const soundtrack=previewMode?{pause(){},dispose(){}}:createMusic($('music'),()=>canvas.focus({preventScroll:true}),{onPower:on=>{antenna?.power(on,{speed:physics?.speed??0,recovering:recovery?.state!=='roof'});if(on)say('Rusty: Raising the antenna. A three-second flex from 2004.')}});
const audio=previewMode?{pause(){},update(){},dispose(){}}:createSound($('sound'),()=>canvas.focus({preventScroll:true}),(on,load)=>soundtrack.setEffectsMix(on,load));
if(!previewMode)audio.pause(true);
const intro=previewMode?null:createDriveIntro($('drive-intro'),$('intro-start'),{onStart:()=>{started=true;setPaused(false)},onExit:exit});
const route=new WaypointRoute(),waypointView=new WaypointView(scene,route,field);
function say(s){$('quip').textContent=s;quipUntil=elapsed+9}
function shiftInput(){return {gas:keys.has('KeyW')||keys.has('ArrowUp')||touch.gas,reverse:keys.has('KeyS')||keys.has('ArrowDown')||touch.brake,cruise}}
function chooseRange(range){if(!loaded||paused||previewMode)return;if(!physics.setRange(range,shiftInput())){say('Rusty: Lift off the gas and turn off cruise to change range. Gravity can keep doing its thing.');return}cancelCruise();document.querySelectorAll('button[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range===range)));$('range-note').textContent=range==='LO'?'LOW SPEED · MORE TORQUE':'HIGH RANGE · CRUISING';$('cruise').title=range==='LO'?'Gentle crawl at about 3 mph':'Gentle cruise at about 8 mph';say(range==='LO'?'Rusty: Low range. More grunt. Less hurry. Soft sand still gets a vote.':'Rusty: High range. Back to beach speed.');canvas.focus({preventScroll:true})}
for(const b of document.querySelectorAll('button[data-range]'))b.addEventListener('click',()=>chooseRange(b.dataset.range));
function toggleCenterLock(){
 if(!loaded||paused||previewMode)return;
 const locked=!physics.centerLocked;
 if(!physics.setCenterLock(locked,shiftInput())){say('Rusty: Lift off the gas and turn off cruise to switch the center lock. Rolling is fine.');canvas.focus({preventScroll:true});return;}
 cancelCruise();$('center-lock').setAttribute('aria-pressed',String(locked));$('center-lock').textContent=locked?'CENTER LOCK · ON':'CENTER LOCK · OFF';
 say(locked?'Rusty: Front and rear now working together. Someone in this vehicle should.':'Rusty: Center unlocked. A little less argument in the corners.');canvas.focus({preventScroll:true});
}
$('center-lock').addEventListener('click',toggleCenterLock);
function deployBoards(){if(!loaded||paused)return;cancelCruise();const result=recovery.deploy();if(result==='ok')say('Rusty: Orange boards. Finally, a sensible impulse purchase. Lock the center and ease forward in 4LO.');else if(result==='moving')say('Rusty: Slow to a crawl first. The boards are not a high-speed delivery service.');else if(result==='tilted')say('Rusty: Boards work on every terrain. Upside down is still a job for Pause → Reset truck.');else say('Rusty: Boards are down. Ease forward, then they’ll return to the rack.');canvas.focus({preventScroll:true})}
$('recover').addEventListener('click',deployBoards);
function cancelCruise(){cruise=false;$('cruise').setAttribute('aria-pressed','false');$('cruise').textContent='Cruise'}
$('cruise').addEventListener('click',()=>{cruise=!cruise;$('cruise').setAttribute('aria-pressed',String(cruise));$('cruise').textContent=cruise?'Cruise on':'Cruise';canvas.focus({preventScroll:true})});
// Graphic sunset palette: dark violet overhead, coral horizon, amber dunes and blue surf.
const skyMat=new THREE.MeshBasicNodeMaterial({side:THREE.BackSide,depthWrite:false,fog:false,toneMapped:false});const sy=positionLocal.y.div(1200);skyMat.colorNode=mix(mix(color('#ed8a75'),color('#f2ad79'),smoothstep(-.03,.025,sy)),color('#49355e'),smoothstep(.015,.30,sy));const sky=new THREE.Mesh(new THREE.SphereGeometry(1200,32,20),skyMat);sky.renderOrder=-20;scene.add(sky);scene.fog=new THREE.Fog('#d59388',180,520);
const sun=new THREE.Mesh(new THREE.SphereGeometry(25,40,24),new THREE.MeshBasicMaterial({color:'#ffe3a0',fog:false}));sun.renderOrder=-10;scene.add(sun);
const hemi=new THREE.HemisphereLight('#a498ca','#855063',1.7);scene.add(hemi);const light=new THREE.DirectionalLight('#ffd39d',2.1);light.castShadow=true;light.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(light.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:1,far:220});light.shadow.bias=-.0002;light.shadow.normalBias=.035;scene.add(light,light.target);
const ocean=new Ocean(scene,{mobile});
const river=new RiverView(scene,ocean);
const clouds=new SunsetClouds(scene,{reduced});
const weatherView=new WeatherView({scene,skyMat,sun,hemi,light,ocean,clouds,mobile,reduced});
const weatherUI=previewMode?null:createWeatherUI(state=>weatherView.set(state));
function waterUpdate(p,t){ocean.update(p,t,physics.origin);river.update(physics.origin)}
let weatherTick=-1;
function expeditionWeather(p){if(!previewMode&&weatherUI?.expedition&&elapsed>=weatherTick){weatherView.set(biomeWeather(p.x,p.z));weatherTick=elapsed+.35;}}
// Recent tread prints add fine detail on top of the physically displaced terrain.
const trackMax=7000,trackMesh=new THREE.InstancedMesh(new THREE.PlaneGeometry(.32,.18),new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.24,depthWrite:false,side:THREE.DoubleSide}),trackMax);trackMesh.count=0;trackMesh.setColorAt(0,new THREE.Color('#654638'));trackMesh.frustumCulled=false;scene.add(trackMesh);let trackCount=0;
function printAt(p,heading){if(surfaceAt(p.x,p.z).grass>.3)return;const ox=physics.origin.x,oz=physics.origin.z,h=field.height(p.x,p.z);const slopeX=(field.height(p.x+.2,p.z)-field.height(p.x-.2,p.z))/.4,slopeZ=(field.height(p.x,p.z+.2)-field.height(p.x,p.z-.2))/.4;dummy.position.set(p.x-ox,h+.018,p.z-oz);dummy.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),new THREE.Vector3(-slopeX,1,-slopeZ).normalize());dummy.rotateZ(heading);dummy.scale.set(1,1,1);dummy.updateMatrix();const slot=trackCount++%trackMax;trackMesh.setMatrixAt(slot,dummy.matrix);const s=surfaceAt(p.x,p.z);trackMesh.setColorAt(slot,new THREE.Color(s.snow>.4?'#96b0c5':s.mud>.4?'#29231f':'#654638'));trackMesh.instanceColor.needsUpdate=true;trackMesh.count=Math.min(trackCount,trackMax);trackMesh.instanceMatrix.needsUpdate=true}
const effects=new SurfaceEffects(scene,field,{mobile,waterHeight:(x,z,t)=>ocean.height(x,z,t)});
const beachLife=new BeachLife(scene,{mobile,reduced});
const atmosphere=new CoastalAtmosphere(scene,field,{mobile,reduced});

function mergeRigid(group){group.updateWorldMatrix(true,true);const inv=group.matrixWorld.clone().invert(),sets=new Map(),remove=[];group.traverse(o=>{if(!o.isMesh)return;let g=o.geometry.clone();g=g.index?g.toNonIndexed():g;for(const name of Object.keys(g.attributes))if(!['position','normal',...(o.material.map?['uv']:[])].includes(name))g.deleteAttribute(name);g.applyMatrix4(inv.clone().multiply(o.matrixWorld));const key=o.material.uuid;if(!sets.has(key))sets.set(key,{mat:o.material,geos:[]});sets.get(key).geos.push(g);remove.push(o)});for(const o of remove)o.removeFromParent();for(const v of sets.values()){const mesh=new THREE.Mesh(mergeGeometries(v.geos),v.mat);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh)}}
function reset(announce=true){recovery?.clear();cancelCruise();const start=loaded&&!previewMode?LANDMARKS[route.next%WAYPOINT_COUNT]:LANDMARKS[0],z=start.z,x=previewMode?shore(z)+18:start.x;terrain.update(x,z);beachLife.refresh({x,z},physics.origin);obstacles.refresh(beachLife);physics.reset(x,z,field.height(x,z));const target=route.target(),yaw=Math.atan2(-(target.x-x),-(target.z-z));physics.rb.setRotation({x:0,y:Math.sin(yaw/2),z:0,w:Math.cos(yaw/2)},true);route.resetTracking();keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);lastStamp=[];effects.clear();ocean.clear();aimHeight=null;camYaw=0;camera.position.set(x-physics.origin.x+7,field.height(x,z)+4,z-physics.origin.z+11);if(announce)say('Rusty: Back on four wheels. We saw nothing.');}
function maybeRebase(){const p=physics.rb.translation();if(Math.abs(p.x)<512&&Math.abs(p.z)<512)return;const x=Math.round(p.x/32)*32,z=Math.round(p.z/32)*32;physics.rebase(x,z);camera.position.x-=x;camera.position.z-=z;terrain.rebase();beachLife.refresh(physics.position(),physics.origin);obstacles.refresh(beachLife);trackCount=trackMesh.count=0;}
function sync(dt){antenna?.restore(camera);const p=physics.position(),local=physics.rb.translation(),rot=physics.rb.rotation();q.set(rot.x,rot.y,rot.z,rot.w);truck.position.set(local.x,local.y,local.z);truck.quaternion.copy(q);truck.translateY(-.70);const f=physics.forward(),heading=Math.atan2(-f.x,-f.z);wheels.forEach((w,i)=>{const length=physics.vehicle.wheelSuspensionLength(i)??.50;w.susp.position.y=.70+.06-length;w.steer.rotation.y=wheelLayout[i].front?physics.steer:0;w.roll.rotation.x=-physics.tyres[i].angle;});
 expeditionWeather(p);if(loaded)vehicleSnow?.update(dt,weatherView.state);vehicleLights?.update(dt,weatherView.state.altitude,physics.lighting,weatherView.state);ocean.updateVehicleLights(vehicleLights);if(vehicleLights)Object.assign(canvas.dataset,{headlights:String(vehicleLights.state.dark),brakeLights:String(vehicleLights.state.braking),reverseLights:String(vehicleLights.state.reversing)});
 recoveryView?.update();$('recover').textContent=recovery?.state==='roof'?'Boards ↓':recovery?.state==='stowing'?'Packing…':recovery?.state==='ground'?'Reposition boards':'Placing boards…';$('recover').setAttribute('aria-disabled',String(recovery?.state==='deploying'||recovery?.state==='stowing'));
 for(const mark of physics.marks.splice(0)){if(effects.emit(mark,heading,physics.speed,elapsed))ocean.disturb(mark,physics.speed,heading);else printAt(mark,heading)}

 const recoveryFocus=!reduced&&(recovery?.state==='deploying'||(recovery?.state==='ground'&&Math.abs(physics.speed)<.5));recoveryCamera+=((recoveryFocus?1:0)-recoveryCamera)*(1-Math.exp(-dt*2));
 let delta=Math.atan2(Math.sin(heading-camYaw),Math.cos(heading-camYaw));camYaw+=delta*(1-Math.exp(-dt*2));const narrow=innerWidth<700,dist=(previewMode?9.5:narrow?13.5:10.5)*(1-recoveryCamera)+2*recoveryCamera,lateral=(previewMode?2:narrow?.5:3.7)*(1-recoveryCamera)+(narrow?15.5:8)*recoveryCamera;temp.set(local.x+Math.sin(camYaw)*dist+Math.cos(camYaw)*lateral,local.y+(previewMode?2.8:narrow?4.1:3.3),local.z+Math.cos(camYaw)*dist-Math.sin(camYaw)*lateral);temp.y=Math.max(temp.y,field.height(temp.x+physics.origin.x,temp.z+physics.origin.z)+2);camera.position.lerp(temp,1-Math.exp(-dt*(reduced?12:4)));const aim=(previewMode?1:3)*(1-recoveryCamera)+.45*recoveryCamera;aimHeight??=local.y+1;aimHeight+=(local.y+1-aimHeight)*(1-Math.exp(-dt*(reduced?12:2.4)));camera.lookAt(local.x+f.x*aim,aimHeight,local.z+f.z*aim);antenna?.camera(camera,field,physics.origin);sky.position.copy(camera.position);sun.position.copy(camera.position).add(new THREE.Vector3(-430,105,-650));light.position.set(local.x-60,local.y+75,local.z-65);light.target.position.set(local.x,local.y,local.z);
 $('game').classList.toggle('driving',physics.travel>8);$('speed').textContent=Math.round(Math.abs(physics.speed)*2.237);const d=p.x-shore(p.z),maxSlip=Math.max(...physics.tyres.map(w=>w.slip)),contacts=[0,1,2,3].filter(i=>physics.vehicle.wheelIsInContact(i)).length;$('surface').textContent=physics.stuck?'BOGGED · EASE OFF':contacts===0?'AIRBORNE':d<6?'SHALLOWS':maxSlip>1.2&&Math.abs(physics.speed)<1?'WHEELSPIN':physics.range==='LO'?'4LO · LOW RANGE':d>43?'4HI · SOFT SAND':'4HI · FIRM SAND';Object.assign(canvas.dataset,{renderer:renderer.backend.isWebGPUBackend?'webgpu':'webgl2',speed:physics.speed.toFixed(2),distance:physics.travel.toFixed(1),ruts:String(field.stamps),depth:field.deepest.toFixed(3),contacts:String(contacts),worldZ:p.z.toFixed(1),fps:String(Math.round(1/Math.max(.001,dt))),height:p.y.toFixed(2),tiles:String(terrain.tiles.size),terrain:'sand-relief-2',water:'bow-wake-2',waterImpulses:String(ocean.wake.impulses),waterDisplacement:ocean.wake.peak.toFixed(3),physics:'rapier-rigid-body',bumpSupport:String(Math.round(physics.bumpSupport||0)),bodyRoll:(Math.atan2(2*(rot.w*rot.z+rot.x*rot.y),1-2*(rot.x*rot.x+rot.z*rot.z))*180/Math.PI).toFixed(1),model:'meshy-radio-1',radio:String(soundtrack.powered??false),antenna:(antenna?.extension??0).toFixed(2),radioCamera:(antenna?.blend??0).toFixed(2),range:physics.range,centerLocked:String(physics.centerLocked),centerTransfer:physics.centerTransfer.toFixed(1),axleSlip:physics.axleSlip.toFixed(3),slip:maxSlip.toFixed(2),wheelRpm:(Math.max(...physics.tyres.map(w=>Math.abs(w.omega)))*60/(Math.PI*2)).toFixed(1),stuck:String(physics.stuck),spray:String(effects.stats.sand),dust:String(effects.stats.dust),splashes:String(effects.stats.splash),wake:String(effects.stats.wake),effects:'tire-spray-1',scenery:'coastal-physics-1',colliders:String(obstacles.colliders.length),clouds:String(clouds.parts.length),grass:String(beachLife.stats.grass),driftwood:String(beachLife.stats.logs),rocks:String(beachLife.stats.rocks),debris:String(beachLife.stats.wrack),boats:String(beachLife.stats.boats),recovery:recovery?.state||'roof',recoveries:String(recovery?.recoveries||0),suspension:[0,1,2,3].map(i=>physics.vehicle.wheelSuspensionLength(i).toFixed(3)).join(',')});
 if(physics.stuck&&elapsed>quipUntil)say('Rusty: Congratulations. You’ve excavated a parking space. Ease off and lock the center. Try reversing—or deploy your boards.');
 const target=route.target();if(!previewMode&&route.update(p,{grounded:contacts>0,groundHeight:field.height(target.x,target.z)})){say(route.passed%WAYPOINT_COUNT===0?'Rusty: Expedition complete. Same beach. Significantly worse laundry. Another lap?':`${target.name} reached. Next: ${route.target().name}.`)}
 const guidance=route.guidance(p,heading),next=route.target(),region=surfaceAt(p.x,p.z),biome=BIOMES[region.biome];
 $('waypoint-name').textContent=next.name.toUpperCase();$('waypoint-distance').textContent=`${Math.round(guidance.distance)} m`;$('waypoint-arrow').style.transform=`rotate(${-guidance.angle}rad)`;
 $('mission').textContent=`${next.leg} / ${WAYPOINT_COUNT} · ${biome.name} · Lap ${Math.floor(route.passed/WAYPOINT_COUNT)+1}`;
 if(!physics.stuck&&contacts>0&&region.biome!=='beach'&&region.biome!=='dunes')$('surface').textContent=biome.name;
 Object.assign(canvas.dataset,{biome:region.biome,expedition:'terrain-loop-1',waypoint:String(next.leg),waypointsPassed:String(route.passed),waypointDistance:guidance.distance.toFixed(1)});

 if(d<4&&elapsed>quipUntil)say('Rusty: Four-wheel drive. Not a submarine.');const up=new THREE.Vector3(0,1,0).applyQuaternion(q);if(up.y<.25&&elapsed>quipUntil)say('Rusty: Excellent view of the tyres. Pause and Reset truck. Boards are not a crane.');waypointView.refresh(physics.origin);beachLife.update(p,elapsed,physics.origin,weatherView.state,heading);atmosphere.update(p,elapsed,physics.origin,camera,weatherView.state);Object.assign(canvas.dataset,{gulls:String(atmosphere.stats.gulls),windSand:String(atmosphere.stats.sand),atmosphere:"coastal-life-1"});return p;
}
function mapDraw(p){
 const c=$('map').getContext('2d'),mx=x=>12+(x+30)*.28,my=z=>12+(z+510)*.275;c.clearRect(0,0,160,180);c.fillStyle='#283d3a';c.fillRect(0,0,160,180);
 c.fillStyle='#416e79';c.fillRect(0,0,12,180);
 c.lineWidth=9;c.lineJoin='round';
 for(let i=1;i<LANDMARKS.length;i++){const a=LANDMARKS[i-1],b=LANDMARKS[i];c.strokeStyle=BIOMES[b.biome].color;c.beginPath();c.moveTo(mx(a.x),my(a.z));c.lineTo(mx(b.x),my(b.z));c.stroke()}
 c.strokeStyle='#80b5c0';c.lineWidth=2;c.beginPath();for(let x=0;x<495;x+=8){const z=riverZ(x);x?c.lineTo(mx(x),my(z)):c.moveTo(mx(x),my(z))}c.stroke();
 c.font='8px monospace';c.fillStyle='#ffffff';for(const [name,x,z] of [['BEACH',0,65],['GRASS',100,-240],['FORD',195,-350],['SNOW',295,-510],['MUD',365,-170]])c.fillText(name,mx(x),my(z));
 const target=route.target();c.fillStyle='#ffc381';c.beginPath();c.arc(mx(target.x),my(target.z),4,0,Math.PI*2);c.fill();
 c.save();c.translate(clamp(mx(p.x),5,155),clamp(my(p.z),5,175));c.rotate(-camYaw);c.fillStyle='#fff';c.strokeStyle='#152d30';c.lineWidth=1;c.beginPath();c.moveTo(0,-5);c.lineTo(-3.5,4);c.lineTo(3.5,4);c.closePath();c.fill();c.stroke();c.restore();
}
function setPaused(value){if(!loaded||(!previewMode&&!started))return;if(previewMode){paused=value;canvas.dataset.previewPaused=String(value);last=performance.now();accumulator=0;return}paused=value;soundtrack.pause(value);if(value)cancelCruise();$('paused').hidden=!value;keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));last=performance.now();accumulator=0;if(!value)canvas.focus({preventScroll:true});audio.pause(value)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer?.setSize(innerWidth,innerHeight)}
function exit(){if(parent!==window)parent.postMessage({type:'lc100:drive-close'},location.origin);else location.href='../#test-drive'}
$('exit').addEventListener('click',exit);$('pause').addEventListener('click',()=>setPaused(true));$('resume').addEventListener('click',()=>setPaused(false));$('reset').addEventListener('click',()=>{reset();setPaused(false)});
const keyboard=createKeyboardControls({keys,state:()=>({loaded:loaded&&(previewMode||started),paused,preview:previewMode}),focus:()=>canvas.focus({preventScroll:true}),cancelCruise,pause:setPaused,range:()=>chooseRange(physics.range==='HI'?'LO':'HI'),recover:deployBoards,lock:toggleCenterLock});
addEventListener('keydown',keyboard.keydown);addEventListener('keyup',keyboard.keyup);addEventListener('blur',()=>{keys.clear();if(loaded&&!previewMode)setPaused(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});addEventListener('resize',resize);
for(const button of document.querySelectorAll('[data-control]')){const key=button.dataset.control;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);touch[key]=true;button.classList.add('pressed')});for(const ev of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(ev,()=>{touch[key]=false;button.classList.remove('pressed')})}

async function init(){try{
 // Single-sample scene depth permits volume occlusion; output FXAA keeps edges smooth.
 renderer=new THREE.WebGPURenderer({canvas,antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,previewMode?1:mobile?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;await renderer.init();scenePass=pass(scene,camera,{samples:0});renderPipeline=new THREE.RenderPipeline(renderer,fxaa(renderOutput(scenePass)));renderPipeline.outputColorTransform=false;intro?.progress(5,'Found the keys. Giving gravity a job.','Starting the drive…');physics=await DrivePhysics.create(field);intro?.progress(10,'Getting the truck off the driveway…','Loading the truck…');terrain=new TerrainView(scene,physics,field);obstacles=new BeachObstacles(physics);$('load-status').textContent='Shaping dunes. Reconsidering the driveway.';
 const ec=document.createElement('canvas');ec.width=512;ec.height=256;const ex=ec.getContext('2d'),eg=ex.createLinearGradient(0,0,0,256);eg.addColorStop(0,'#574b7e');eg.addColorStop(.42,'#ce96a7');eg.addColorStop(.5,'#ffd19a');eg.addColorStop(.57,'#c37c65');eg.addColorStop(1,'#63475d');ex.fillStyle=eg;ex.fillRect(0,0,512,256);const et=new THREE.CanvasTexture(ec);et.mapping=THREE.EquirectangularReflectionMapping;et.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(et).texture;scene.environmentIntensity=.6;pmrem.dispose();et.dispose();
 intro?.progress(15,'Getting the truck off the driveway…','Loading the truck…');const gltf=await new GLTFLoader().loadAsync('lc100.glb?v=radio-1',event=>{if(event.total>0)intro?.progress(15+20*event.loaded/event.total,`Truck download: ${Math.floor(100*event.loaded/event.total)}%.`,'Loading the truck…')});intro?.progress(35,'Packing the recovery boards. Optimism only gets you so far.','Packing the boards…');truck=gltf.scene;scene.add(truck);antenna=new PowerAntenna(truck,{reduced});for(const w of wheelLayout){const susp=truck.getObjectByName('Susp_'+w.name),st=truck.getObjectByName('Steer_'+w.name),roll=truck.getObjectByName('Roll_'+w.name);wheels.push({susp,steer:st,roll});mergeRigid(roll)}mergeRigid(truck.getObjectByName('Body'));vehicleLights=new VehicleLights(truck,{mobile,reduced});vehicleSnow=new VehicleSnow(truck);recovery=new Recovery(physics);const boards=await new GLTFLoader().loadAsync('traction-board.glb?v=recovery-1',event=>{if(event.total>0)intro?.progress(35+3*event.loaded/event.total,undefined,'Packing the boards…')});intro?.progress(38,'Shaping dunes. Reconsidering your confidence.','Building the route…');recoveryView=new RecoveryView(scene,truck,boards.scene,recovery);reset(false);for(let i=0;i<240;i++)physics.step(1/120,{turn:0,brake:true});if(!previewMode){physics.rb.setLinvel({x:0,y:0,z:0},true);physics.rb.setAngvel({x:0,y:0,z:0},true);physics.speed=0;}physics.soundEvents.length=0;sync(1);waterUpdate(physics.position(),0);terrain.animate(0);clouds.update(camera,0);mapDraw(physics.position());if(!previewMode)weatherView.update(10,camera,physics.rb.translation(),renderer);intro?.progress(40,'Downloads done. Getting the scene ready.','Preparing the expedition…');await new Promise(requestAnimationFrame);await renderer.compileAsync(scene,camera,null,event=>{if(event.total>0)intro?.progress(40+55*event.loaded/event.total,`${event.loaded} of ${event.total} scene pieces ready.`,'Preparing the expedition…')});intro?.busy('Drawing the first frame…','One last look before we give you the keys.');await new Promise(requestAnimationFrame);loaded=true;$('loading').hidden=true;if(previewMode){paused=!previewActive;renderPipeline.render();parent.postMessage({type:'lc100:preview-ready'},location.origin)}else{paused=true;weatherView.update(10,camera,physics.rb.translation(),renderer);renderPipeline.render();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));intro.ready();}last=performance.now();renderer.setAnimationLoop(frame);
 }catch(e){intro?.fail();console.error('Beach drive initialization failed',e);$('load-status').textContent='This browser couldn’t start the 3D drive. Try a recent browser with graphics acceleration enabled.';document.querySelector('.loadline').hidden=true;const b=document.createElement('button');b.className='primary';b.textContent='Back to the truck';b.addEventListener('click',exit);$('loading').append(b)}}
function frame(now){if(dead)return;const dt=Math.min(.06,(now-last)/1000);last=now;if(paused)return;elapsed+=dt;frameCount++;const input={gas:keys.has('KeyW')||keys.has('ArrowUp')||touch.gas,reverse:keys.has('KeyS')||keys.has('ArrowDown')||touch.brake,brake:keys.has('Space'),turn:(keys.has('KeyA')||keys.has('ArrowLeft')||touch.left?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')||touch.right?1:0),cruise};antenna?.update(dt,{driving:!!(input.gas||input.reverse||input.brake||input.turn),recovering:recovery?.state!=='roof'});if(antenna?.holding){input.brake=true;input.cruise=false;}if(input.reverse||input.brake){cancelCruise();input.cruise=false}const p=physics.position();if(previewMode){const f=physics.forward(),heading=Math.atan2(-f.x,-f.z),desired=Math.atan2(-(shore(p.z-15)+18-p.x),15),error=Math.atan2(Math.sin(desired-heading),Math.cos(desired-heading));input.turn=clamp(error*2.4,-1,1);input.cruise=true;}terrain.update(p.x,p.z);beachLife.refresh(p,physics.origin);obstacles.refresh(beachLife);accumulator+=dt;let steps=0;while(accumulator>=1/120&&steps++<8){physics.step(1/120,input);accumulator-=1/120}maybeRebase();const pos=sync(dt);if(frameCount%8===0)terrain.refresh();waterUpdate(pos,elapsed);ocean.updateWheelFoam(dt,physics,elapsed);terrain.animate(elapsed);clouds.update(camera,elapsed);if(!previewMode)weatherView.update(dt,camera,physics.rb.translation(),renderer);if(frameCount%5===0)mapDraw(pos);effects.update(dt,camera,physics.origin,elapsed);audio.update({impacts:physics.soundEvents.splice(0),speed:physics.speed,tyres:physics.tyres,range:physics.range,input,shoreDistance:pos.x-shore(pos.z),waterContact:physics.tyres.reduce((n,w,i)=>{const c=physics.vehicle.wheelContactPoint(i);if(!w.contact||!c)return n;const x=c.x+physics.origin.x,z=c.z+physics.origin.z;return n+(waterExists(x,z)&&ocean.height(x,z,elapsed)>c.y+.025?1:0)},0)/4});renderPipeline.render()}
addEventListener('message',event=>{if(!previewMode||event.source!==parent||event.origin!==location.origin||event.data?.type!=='lc100:preview-active')return;previewActive=event.data.active===true&&!document.hidden;setPaused(!previewActive)});
addEventListener('pagehide',()=>{dead=true;intro?.dispose();vehicleSnow?.dispose();vehicleLights?.dispose();weatherUI?.dispose();weatherView.dispose();atmosphere.dispose();soundtrack.dispose();renderer?.setAnimationLoop(null);obstacles?.dispose();physics?.dispose();clouds.dispose();river.dispose();ocean.dispose();effects.dispose();beachLife.dispose();waypointView.dispose();renderPipeline?.dispose();scenePass?.dispose();renderer?.dispose();audio.dispose()},{once:true});init();
