// Judge Dean LLC — keep gameplay gated until a new or saved expedition is chosen.
export function createDriveIntro(dialog,start,{onStart,onContinue,onExit,savedCheckpoint=null}){
 let ready=false,started=false,failed=false,percent=0;
 const label=start.querySelector('[data-intro-label]'),meter=dialog.querySelector('[data-intro-progress]'),status=dialog.querySelector('[data-intro-status]');
 const fresh=dialog.querySelector('[data-intro-new]'),saved=dialog.querySelector('[data-intro-saved]');
 fresh.hidden=!savedCheckpoint;fresh.disabled=true;saved.hidden=!savedCheckpoint;saved.textContent=savedCheckpoint?`Saved checkpoint: ${savedCheckpoint}. Continue your expedition, or start over with a fresh route.`:'';
 const progress=(value,message,caption)=>{if(ready||failed||!Number.isFinite(value))return;percent=Math.max(percent,Math.min(95,Math.round(value)));start.style.setProperty('--load-progress',percent+'%');start.dataset.loading='progress';label.textContent=caption||`Getting the keys… ${percent}%`;meter.setAttribute('aria-valuenow',String(percent));meter.setAttribute('aria-valuetext',caption||`${percent}% loaded`);if(message)status.textContent=message};
 const busy=(caption,message)=>{if(ready||failed)return;start.dataset.loading='busy';label.textContent=caption;meter.removeAttribute('aria-valuenow');meter.setAttribute('aria-valuetext',caption);if(message)status.textContent=message};
 const launch=callback=>{if(!ready||failed||started)return;started=true;start.disabled=fresh.disabled=true;dialog.close();callback()};
 const begin=()=>launch(savedCheckpoint?onContinue:onStart),beginNew=()=>launch(onStart);
 const cancel=e=>e.preventDefault(),leave=()=>onExit();
 start.disabled=true;progress(0);busy('Finding the keys…','Starting the drive. Still no errands.');dialog.addEventListener('cancel',cancel);start.addEventListener('click',begin);fresh.addEventListener('click',beginNew);
 const exit=dialog.querySelector('[data-intro-exit]');exit.addEventListener('click',leave);dialog.showModal();
 return {progress,busy,ready(){if(failed)return;ready=true;start.dataset.loading='ready';start.style.setProperty('--load-progress','100%');meter.setAttribute('aria-valuenow','100');meter.setAttribute('aria-valuetext','Ready to drive');start.disabled=false;fresh.disabled=false;label.textContent=savedCheckpoint?'Continue':'Start new';status.textContent=savedCheckpoint?'Progress is saved in this browser. Start new replaces your saved expedition.':'Progress saves in this browser at each checkpoint.'},fail(){failed=true;fresh.disabled=true;start.dataset.loading='failed';start.disabled=true;meter.removeAttribute('aria-valuenow');meter.setAttribute('aria-valuetext','Loading failed');label.textContent='Keys unavailable';status.textContent='The beach couldn’t load. Try a recent browser with graphics acceleration.'},dispose(){dialog.removeEventListener('cancel',cancel);start.removeEventListener('click',begin);fresh.removeEventListener('click',beginNew);exit.removeEventListener('click',leave);if(dialog.open)dialog.close()}};
}
