import * as THREE from 'three/webgpu';
import {positionLocal,mix,color,smoothstep} from 'three/tsl';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp;
const mobile=matchMedia('(pointer: coarse)').matches||innerWidth<700;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(parent!==window)$('exit').hidden=true;
const canvas=$('view'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.15,1100);
let renderer,truck,body,wheels=[],paused=false,loaded=false,dead=false,last=0,accumulator=0,elapsed=0,speed=0,steer=0,yaw=0,roll=0,distance=0,trackIndex=0,lastTrack=new THREE.Vector3(),normalTick=0;
const car=new THREE.Vector3(6,0,105),keys=new Set(),touch={left:false,right:false,gas:false,brake:false};
const bounds={x0:-43,x1:88,z0:-170,z1:170,nx:256,nz:680};const dx=(bounds.x1-bounds.x0)/bounds.nx,dz=(bounds.z1-bounds.z0)/bounds.nz;
const discoveries=new Set(),stops=[{x:12,z:40,label:'THE CAMPSITE',quip:'Rusty: A tent, a sunset, and absolutely no Wi-Fi password.'},{x:48,z:-45,label:'THE DUNE LOOKOUT',quip:'Rusty: That view is not available in the Home Depot car park.'},{x:-14,z:-133,label:'SUNSET POINT',quip:'Rusty: Okay. I understand why you’re having trouble selling it.'}];
let quipUntil=0,audio=null,cruise=false;
function cancelCruise(){cruise=false;$("cruise").setAttribute("aria-pressed","false");$("cruise").textContent="Cruise"}
$("cruise").addEventListener("click",()=>{cruise=!cruise;$("cruise").setAttribute("aria-pressed",String(cruise));$("cruise").textContent=cruise?"Cruise on":"Cruise";canvas.focus({preventScroll:true})});
function say(text){$('quip').textContent=text;quipUntil=elapsed+9}
function baseHeight(x,z){const inland=Math.max(0,x+25);const dunes=Math.max(0,x-14)/38;return .02+inland*.008+Math.sin(z*.055+x*.085)*.07+Math.sin(z*.15-x*.16)*.025+Math.min(1.8,dunes)*(.75+.65*Math.sin(z*.035+x*.045))}
function makeGrid(nx,nz,x0,x1,z0,z1,height){const g=new THREE.BufferGeometry(),p=new Float32Array((nx+1)*(nz+1)*3),uv=new Float32Array((nx+1)*(nz+1)*2),idx=[];for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){const k=j*(nx+1)+i,x=x0+(x1-x0)*i/nx,z=z0+(z1-z0)*j/nz;p.set([x,height(x,z),z],k*3);uv.set([i/nx,j/nz],k*2);if(i<nx&&j<nz){const a=k,b=k+1,c=k+nx+1,d=c+1;idx.push(a,c,b,b,c,d)}}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
const sandGeo=makeGrid(bounds.nx,bounds.nz,bounds.x0,bounds.x1,bounds.z0,bounds.z1,baseHeight),heights=sandGeo.attributes.position.array,original=heights.slice();
function heightAt(x,z){const ix=clamp((x-bounds.x0)/dx,0,bounds.nx-.001),iz=clamp((z-bounds.z0)/dz,0,bounds.nz-.001),i=Math.floor(ix),j=Math.floor(iz),u=ix-i,v=iz-j,k=(j*(bounds.nx+1)+i)*3;return THREE.MathUtils.lerp(THREE.MathUtils.lerp(heights[k+1],heights[k+4],u),THREE.MathUtils.lerp(heights[k+(bounds.nx+1)*3+1],heights[k+(bounds.nx+1)*3+4],u),v)}
function stamp(x,z){const i=Math.round((x-bounds.x0)/dx),j=Math.round((z-bounds.z0)/dz);for(let b=-2;b<=2;b++)for(let a=-2;a<=2;a++){const u=i+a,v=j+b;if(u<1||u>=bounds.nx||v<1||v>=bounds.nz)continue;const k=(v*(bounds.nx+1)+u)*3,r=Math.hypot(heights[k]-x,heights[k+2]-z);if(r>.65)continue;const depth=.055*Math.exp(-r*r/ .065);heights[k+1]=Math.max(original[k+1]-.19,heights[k+1]-depth)}sandGeo.attributes.position.needsUpdate=true}
function grain(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),d=ctx.createImageData(256,256);let seed=713;for(let i=0;i<d.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const v=175+(seed>>>24)*.25;d.data.set([v,v*.94,v*.82,255],i)}ctx.putImageData(d,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(110,270);t.colorSpace=THREE.SRGBColorSpace;return t}
const sandColor=new Float32Array(heights.length);const dry=new THREE.Color('#bd9670'),wet=new THREE.Color('#705d4c');for(let k=0;k<heights.length;k+=3){const c=dry.clone().lerp(wet,1-smoothNum(-27,-14,heights[k]));sandColor.set([c.r,c.g,c.b],k)}sandGeo.setAttribute('color',new THREE.BufferAttribute(sandColor,3));
function smoothNum(a,b,v){v=clamp((v-a)/(b-a),0,1);return v*v*(3-2*v)}
const sandMat=new THREE.MeshStandardMaterial({color:0xffffff,map:grain(),vertexColors:true,roughness:.92,metalness:.02});const sand=new THREE.Mesh(sandGeo,sandMat);sand.receiveShadow=true;scene.add(sand);
const skyMat=new THREE.MeshBasicNodeMaterial({side:THREE.BackSide,depthWrite:false,fog:false});const sy=positionLocal.y.div(900);skyMat.colorNode=mix(mix(color('#d3876b'),color('#dab48e'),smoothstep(-.03,.03,sy)),color('#263f68'),smoothstep(.015,.28,sy));scene.add(new THREE.Mesh(new THREE.SphereGeometry(900,32,24),skyMat));
scene.fog=new THREE.FogExp2('#c09279',.0024);
const sun=new THREE.Mesh(new THREE.SphereGeometry(13,32,20),new THREE.MeshBasicMaterial({color:'#ffe1a0',fog:false}));sun.position.set(-220,35,-340);scene.add(sun);
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=128;const gc=glowCanvas.getContext('2d'),grad=gc.createRadialGradient(64,64,2,64,64,64);grad.addColorStop(0,'rgba(255,213,133,.65)');grad.addColorStop(.3,'rgba(255,163,98,.3)');grad.addColorStop(1,'rgba(255,133,86,0)');gc.fillStyle=grad;gc.fillRect(0,0,128,128);const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,depthWrite:false,fog:false}));glow.position.copy(sun.position);glow.scale.set(150,150,1);scene.add(glow);
scene.add(new THREE.HemisphereLight('#afc5df','#71513d',2.0));const sunlight=new THREE.DirectionalLight('#ffba7c',3.4);sunlight.position.set(-65,70,-70);sunlight.castShadow=true;sunlight.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);sunlight.shadow.camera.left=-16;sunlight.shadow.camera.right=16;sunlight.shadow.camera.top=16;sunlight.shadow.camera.bottom=-16;sunlight.shadow.camera.near=1;sunlight.shadow.camera.far=200;sunlight.shadow.bias=-.0006;sunlight.shadow.normalBias=.06;scene.add(sunlight,sunlight.target);
const waterGeo=makeGrid(78,130,-430,-28,-510,310,()=>-.09),waterPos=waterGeo.attributes.position.array;
const waterMat=new THREE.MeshStandardMaterial({color:'#647f80',roughness:.21,metalness:.64,transparent:true,opacity:.93});const water=new THREE.Mesh(waterGeo,waterMat);water.receiveShadow=true;scene.add(water);
const foamLayers=[];for(let l=0;l<3;l++){const g=new THREE.BufferGeometry(),p=new Float32Array(401*2*3),uv=new Float32Array(401*2*2),idx=[];for(let j=0;j<400;j++){const k=j*2;idx.push(k,k+1,k+2,k+1,k+3,k+2)}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setIndex(idx);const mat=new THREE.MeshBasicMaterial({color:'#f3d9b6',transparent:true,opacity:.43,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,mat);mesh.frustumCulled=false;scene.add(mesh);foamLayers.push({g,p,mat,l})}
function animateWater(t){for(let k=0;k<waterPos.length;k+=3){const x=waterPos[k],z=waterPos[k+2],near=smoothNum(-28,-48,x);waterPos[k+1]=-.10+(Math.sin(x*.29+t*1.6+z*.015)*.25+Math.sin(x*.11-t*.8+z*.045)*.18+Math.sin(z*.27+t*.7)*.06)*near}waterGeo.attributes.position.needsUpdate=true;if(normalTick%3===0)waterGeo.computeVertexNormals();for(const f of foamLayers){const phase=(t*.16+f.l/3)%1,run=Math.sin(phase*Math.PI);f.mat.opacity=.48*Math.sin(phase*Math.PI);for(let j=0;j<=400;j++){const z=-190+j,front=-36+run*8+Math.sin(z*.08-t*.6)*.4;const width=.18+Math.pow(1-run,1.3)*1.3;for(let edge=0;edge<2;edge++){const x=front-edge*width,k=(j*2+edge)*3;f.p[k]=x;f.p[k+1]=Math.max(.04,heightAt(x,clamp(z,-169,169))+.024)+Math.sin(z*.5+t)*.015;f.p[k+2]=z}}f.g.attributes.position.needsUpdate=true}}
// A field of small sun glints follows the moving sea, rather than a painted reflection.
const sparkle=new THREE.InstancedMesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({color:'#ffe3ac',transparent:true,opacity:.4,depthWrite:false,side:THREE.DoubleSide}),100);const dummy=new THREE.Object3D();for(let i=0;i<100;i++){dummy.position.set(-55-(i%10)*6,.36,-160+Math.floor(i/10)*10+Math.sin(i)*8);dummy.rotation.set(-Math.PI/2,0,0);dummy.scale.set(1+Math.random()*3,.06+Math.random()*.18,1);dummy.updateMatrix();sparkle.setMatrixAt(i,dummy.matrix)}scene.add(sparkle);
const trackMax=5000,tracks=new THREE.InstancedMesh(new THREE.PlaneGeometry(.28,.28),new THREE.MeshBasicMaterial({color:'#625547',transparent:true,opacity:.30,depthWrite:false,side:THREE.DoubleSide}),trackMax);tracks.count=0;tracks.frustumCulled=false;scene.add(tracks);
function tirePrint(x,z){stamp(x,z);dummy.position.set(x,heightAt(x,z)+.017,z);dummy.rotation.set(-Math.PI/2,0,-yaw);dummy.scale.set(1,1,1);dummy.updateMatrix();tracks.setMatrixAt(trackIndex%trackMax,dummy.matrix);trackIndex++;tracks.count=Math.min(trackIndex,trackMax);tracks.instanceMatrix.needsUpdate=true}
const props=new THREE.Group();scene.add(props);function box(w,h,d,mat,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;props.add(m);return m}
const drift=new THREE.MeshStandardMaterial({color:'#625547',roughness:1}),fabric=new THREE.MeshStandardMaterial({color:'#b67c48',roughness:1,side:THREE.DoubleSide});
for(const stop of stops){const y=heightAt(stop.x,stop.z);box(.09,2.5,.09,drift,stop.x,y+1.25,stop.z);box(1.1,.55,.05,fabric,stop.x+.5,y+2.2,stop.z)}
// Small campsite and driftwood give the beach a human scale.
const tentGeo=new THREE.ConeGeometry(2.1,1.8,3,1,false);const tent=new THREE.Mesh(tentGeo,new THREE.MeshStandardMaterial({color:'#496861',roughness:.9}));tent.position.set(17,heightAt(17,39)+.9,39);tent.rotation.y=.5;tent.castShadow=true;scene.add(tent);
for(let i=0;i<24;i++){const x=36+Math.sin(i*2.3)*22,z=-150+i*12.8;const log=box(.16,.12,1.7+Math.random()*2,drift,x,heightAt(x,z)+.09,z);log.rotation.y=i*1.7}
const grassMat=new THREE.MeshStandardMaterial({color:'#81734b',side:THREE.DoubleSide,roughness:1});const grass=new THREE.InstancedMesh(new THREE.PlaneGeometry(.13,.75),grassMat,500);for(let i=0;i<500;i++){const x=43+Math.random()*36,z=-165+Math.random()*330;dummy.position.set(x,heightAt(x,z)+.3,z);dummy.rotation.set(.1,Math.random()*Math.PI,Math.sin(i)*.2);dummy.scale.set(1,.4+Math.random(),1);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix)}scene.add(grass);
const dustN=140,dustData=[],dust=new THREE.InstancedMesh(new THREE.PlaneGeometry(.45,.45),new THREE.MeshBasicMaterial({color:'#c5a27d',map:new THREE.CanvasTexture(glowCanvas),transparent:true,opacity:.13,depthWrite:false,side:THREE.DoubleSide}),dustN);dust.frustumCulled=false;for(let i=0;i<dustN;i++)dustData.push({life:0,p:new THREE.Vector3(),v:new THREE.Vector3()});scene.add(dust);let dustCursor=0;
function emitDust(x,z){const p=dustData[dustCursor++%dustN];p.life=1;p.p.set(x,heightAt(x,z)+.05,z);p.v.set(Math.random()*.7-.35,.4+Math.random()*.6,Math.random()*.7-.35)}
function mergeRigid(group){group.updateWorldMatrix(true,true);const inv=group.matrixWorld.clone().invert(),sets=new Map(),remove=[];group.traverse(o=>{if(!o.isMesh)return;let g=o.geometry.clone();g=g.index?g.toNonIndexed():g;for(const name of Object.keys(g.attributes))if(!['position','normal'].includes(name))g.deleteAttribute(name);g.applyMatrix4(inv.clone().multiply(o.matrixWorld));const key=o.material.uuid;if(!sets.has(key))sets.set(key,{mat:o.material,geos:[]});sets.get(key).geos.push(g);remove.push(o)});for(const o of remove)o.removeFromParent();for(const v of sets.values()){const merged=mergeGeometries(v.geos);const mesh=new THREE.Mesh(merged,v.mat);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh)}}
function wheelWorld(w){const x=w.rest.x,z=w.rest.z;return {x:car.x+Math.cos(yaw)*x+Math.sin(yaw)*z,z:car.z-Math.sin(yaw)*x+Math.cos(yaw)*z}}
function reset(announce=true){cancelCruise();car.set(6,0,105);speed=steer=yaw=roll=0;keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);if(truck){truck.position.copy(car);truck.rotation.y=0}camera.position.set(car.x+8,car.y+5,car.z+11);lastTrack.copy(car);if(announce)say('Rusty: Back on the firm sand. Let’s call that a strategic retreat.');sync(0)}
function step(dt){const gas=keys.has('KeyW')||keys.has('ArrowUp')||touch.gas,back=keys.has('KeyS')||keys.has('ArrowDown')||touch.brake,brake=keys.has('Space'),turn=(keys.has('KeyA')||keys.has('ArrowLeft')||touch.left?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')||touch.right?1:0);steer=THREE.MathUtils.damp(steer,turn*.45,7,dt);if(back||brake)cancelCruise();const softness=smoothNum(10,55,car.x),prior=speed;let acc=gas?4.2*(1-softness*.35):(cruise?clamp((5.4-speed)*2,-2,3):0);if(back)acc-=speed>1?9:2.8;if(brake)acc-=Math.sign(speed)*12;acc-=Math.sign(speed)*(.25+speed*speed*(.008+softness*.016));speed=clamp(speed+acc*dt,-4.5,14);if(!gas&&!back&&!cruise&&Math.abs(speed)<.08)speed=0;if(brake&&Math.sign(prior)!==Math.sign(speed))speed=0;yaw+=speed*Math.tan(steer)/2.85*dt;car.x-=Math.sin(yaw)*speed*dt;car.z-=Math.cos(yaw)*speed*dt;distance+=Math.abs(speed)*dt;roll-=speed*dt/.48;
 const nx=clamp(car.x,-24,77),nz=clamp(car.z,-155,155);if(nx!==car.x||nz!==car.z){car.x=nx;car.z=nz;speed*=-.22;if(elapsed>quipUntil)say('Rusty: That’s the edge of our beach. Try steering.')}return (speed-prior)/dt}
function sync(dt,acc=0){if(!truck)return;let sum=0;const levels=[];for(const w of wheels){const p=wheelWorld(w),h=heightAt(p.x,p.z);levels.push(h);sum+=h}car.y=THREE.MathUtils.damp(car.y,sum/4,dt?9:1000,dt||1);truck.position.copy(car);truck.rotation.y=yaw;body.rotation.z=THREE.MathUtils.damp(body.rotation.z,clamp(steer*speed*.014,-.10,.10)+(levels[0]+levels[1]-levels[2]-levels[3])*.12,6,dt);body.rotation.x=THREE.MathUtils.damp(body.rotation.x,clamp(-acc*.009,-.06,.06)+(levels[0]+levels[2]-levels[1]-levels[3])*.13,6,dt);wheels.forEach((w,i)=>{w.susp.position.y=w.rest.y+clamp(levels[i]-car.y,-.22,.22);w.steer.rotation.y=w.front?steer:0;w.roll.rotation.x=roll});
 if(car.distanceTo(lastTrack)>.25&&Math.abs(speed)>.2){for(const w of wheels){const p=wheelWorld(w);tirePrint(p.x,p.z);if(!w.front&&Math.abs(speed)>5&&car.x>-15&&Math.random()<.5)emitDust(p.x,p.z)}lastTrack.copy(car)}
 for(const stop of stops)if(!discoveries.has(stop.label)&&Math.hypot(car.x-stop.x,car.z-stop.z)<9){discoveries.add(stop.label);say(stop.quip);$('mission').textContent=discoveries.size===3?'All three stops found. Stay as long as you like.':`${discoveries.size} / 3 stops found · ${stop.label.toLowerCase()}`}
 const narrow=innerWidth<700,follow=narrow?13:10,lateral=narrow?.5:3;const desired=new THREE.Vector3(car.x+Math.sin(yaw)*follow+Math.cos(yaw)*lateral,car.y+(narrow?4.8:4.1),car.z+Math.cos(yaw)*follow-Math.sin(yaw)*lateral);camera.position.lerp(desired,1-Math.exp(-dt*(reduced?9:3.4)));camera.position.y=Math.max(camera.position.y,heightAt(clamp(camera.position.x,-42,87),clamp(camera.position.z,-169,169))+1.5);camera.lookAt(car.x-Math.sin(yaw)*4,car.y+1.25,car.z-Math.cos(yaw)*4);sunlight.position.set(car.x-65,car.y+70,car.z-70);sunlight.target.position.copy(car);$('speed').textContent=Math.round(Math.abs(speed)*2.237);$('surface').textContent=car.x>25?'SOFT SAND':speed<-.2?'REVERSE':'FIRM SAND';canvas.dataset.speed=speed.toFixed(2);canvas.dataset.distance=distance.toFixed(1);canvas.dataset.ruts=String(trackIndex);}
const mapCtx=$('map').getContext('2d');function mapDraw(){const c=mapCtx;c.clearRect(0,0,160,180);c.fillStyle='#667f82';c.fillRect(0,0,29,180);c.fillStyle='#ae947555';c.fillRect(29,0,131,180);const point=(x,z)=>[29+(x+25)/105*125,8+(z+160)/320*164];for(const s of stops){const [x,y]=point(s.x,s.z);c.fillStyle=discoveries.has(s.label)?'#ffd099':'#ffffff88';c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill()}const [x,y]=point(car.x,car.z);c.save();c.translate(x,y);c.rotate(-yaw);c.fillStyle='#fff4d8';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,5);c.lineTo(4,5);c.closePath();c.fill();c.restore()}
function setPaused(value){if(!loaded)return;paused=value;if(value)cancelCruise();$('paused').hidden=!value;keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));last=performance.now();accumulator=0;if(!value)canvas.focus({preventScroll:true});if(audio)audio.master.gain.setTargetAtTime(value||!audio.on?0:.09,audio.ctx.currentTime,.1)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer?.setSize(innerWidth,innerHeight)}
function exit(){if(parent!==window)parent.postMessage({type:'lc100:drive-close'},location.origin);else location.href='../#test-drive'}
$('exit').addEventListener('click',exit);$('pause').addEventListener('click',()=>setPaused(true));$('resume').addEventListener('click',()=>setPaused(false));$('reset').addEventListener('click',()=>{reset();setPaused(false)});
addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();setPaused(!paused);return}if(e.code==='KeyR'){reset();return}if(['Space','KeyS','ArrowDown'].includes(e.code))cancelCruise();if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&!['BUTTON','INPUT'].includes(e.target.tagName)){e.preventDefault();keys.add(e.code)}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(loaded)setPaused(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});addEventListener('resize',resize);
for(const button of document.querySelectorAll('[data-control]')){const key=button.dataset.control;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);touch[key]=true;button.classList.add('pressed')});for(const ev of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(ev,()=>{touch[key]=false;button.classList.remove('pressed')})}
$('sound').addEventListener('click',async()=>{try{if(!audio){const ctx=new AudioContext(),master=ctx.createGain(),engine=ctx.createOscillator(),filter=ctx.createBiquadFilter();master.gain.value=.09;master.connect(ctx.destination);engine.type='sawtooth';filter.type='lowpass';filter.frequency.value=160;engine.connect(filter);const eg=ctx.createGain();eg.gain.value=.35;filter.connect(eg);eg.connect(master);engine.start();const b=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*.1;const surf=ctx.createBufferSource();surf.buffer=b;surf.loop=true;surf.connect(master);surf.start();audio={ctx,master,engine,on:true}}else audio.on=!audio.on;await audio.ctx.resume();audio.master.gain.setTargetAtTime(audio.on&&!paused?.09:0,audio.ctx.currentTime,.15);$('sound').textContent=audio.on?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(audio.on));canvas.focus()}catch{$('sound').textContent='Sound unavailable'}});
async function init(){try{renderer=new THREE.WebGPURenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.35:1.7));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;await renderer.init();
 const ec=document.createElement('canvas');ec.width=512;ec.height=256;const ex=ec.getContext('2d'),eg=ex.createLinearGradient(0,0,0,256);eg.addColorStop(0,'#536584');eg.addColorStop(.35,'#a9b6c4');eg.addColorStop(.49,'#efc1a0');eg.addColorStop(.52,'#cfa078');eg.addColorStop(1,'#705647');ex.fillStyle=eg;ex.fillRect(0,0,512,256);const et=new THREE.CanvasTexture(ec);et.mapping=THREE.EquirectangularReflectionMapping;et.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(et).texture;scene.environmentIntensity=.9;
 canvas.dataset.renderer=renderer.backend.isWebGPUBackend?'webgpu':'webgl2';$('load-status').textContent='Checking the tyre pressure. Emotionally, at least.';const gltf=await new GLTFLoader().loadAsync('lc100.glb');truck=gltf.scene;body=truck.getObjectByName('Body');scene.add(truck);for(const side of ['L','R'])for(const end of ['F','R']){const name=end+side,susp=truck.getObjectByName('Susp_'+name),st=truck.getObjectByName('Steer_'+name),r=truck.getObjectByName('Roll_'+name);wheels.push({susp,steer:st,roll:r,rest:susp.position.clone(),front:end==='F'});mergeRigid(r)}mergeRigid(body);reset(false);await renderer.compileAsync(scene,camera);loaded=true;$('loading').hidden=true;canvas.focus();last=performance.now();renderer.setAnimationLoop(frame)}catch(e){console.error('Beach drive initialization failed',e);$('load-status').textContent='This browser couldn’t start the 3D drive. Try a recent browser with graphics acceleration enabled.';document.querySelector('.loadline').hidden=true;const b=document.createElement('button');b.className='primary';b.textContent='Back to the truck';b.addEventListener('click',exit);$('loading').append(b)}}
function frame(now){if(dead)return;const dt=Math.min(.06,(now-last)/1000);last=now;if(paused)return;elapsed+=dt;normalTick++;accumulator+=dt;let acc=0;while(accumulator>=1/120){acc=step(1/120);accumulator-=1/120}sync(dt,acc);animateWater(elapsed);if(normalTick%12===0&&Math.abs(speed)>.1)sandGeo.computeVertexNormals();for(let i=0;i<dustN;i++){const d=dustData[i];d.life=Math.max(0,d.life-dt*.65);d.p.addScaledVector(d.v,dt);dummy.position.copy(d.p);dummy.quaternion.copy(camera.quaternion);dummy.scale.setScalar(d.life>0?Math.sin(d.life*Math.PI)*3:0);dummy.updateMatrix();dust.setMatrixAt(i,dummy.matrix)}dust.instanceMatrix.needsUpdate=true;if(audio)audio.engine.frequency.setTargetAtTime(28+Math.abs(speed)*3.5,audio.ctx.currentTime,.15);if(normalTick%5===0)mapDraw();renderer.render(scene,camera)}
addEventListener('pagehide',()=>{dead=true;renderer?.setAnimationLoop(null);renderer?.dispose();audio?.ctx.close()},{once:true});init();
