import {createMusic} from './music.mjs';
import * as THREE from 'three/webgpu';
import {positionLocal,mix,color,smoothstep} from 'three/tsl';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RANGES} from './drivetrain.mjs';
import {DrivePhysics,wheelLayout} from './physics.mjs';
import {SandField,baseHeight,shore,smooth,clamp} from './terrain.mjs';
import {TerrainView} from './terrain-view.mjs';
const previewMode=new URLSearchParams(location.search).get('preview')==='1';
if(previewMode)document.documentElement.classList.add('preview-mode');
let previewActive=false;
const $=id=>document.getElementById(id),canvas=$('view'),mobile=matchMedia('(pointer:coarse)').matches||innerWidth<700,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(parent!==window)$('exit').hidden=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,1500),field=new SandField();
let renderer,physics,terrain,truck,wheels=[],paused=false,loaded=false,dead=false,last=0,accumulator=0,elapsed=0,frameCount=0,cruise=false,audio=null,quipUntil=0,camYaw=0,lastStamp=[],waterCenter=Infinity;
const keys=new Set(),touch={left:false,right:false,gas:false,brake:false},temp=new THREE.Vector3(),dummy=new THREE.Object3D(),q=new THREE.Quaternion();
const soundtrack=previewMode?{pause(){},dispose(){}}:createMusic($('music'),()=>canvas.focus({preventScroll:true}));
const stopSet=new Set();let stops=[];
function say(s){$('quip').textContent=s;quipUntil=elapsed+9}
function chooseRange(range){if(!loaded)return;if(!physics.setRange(range)){say('Rusty: Slow to a stop before changing range. Even imaginary transfer cases have feelings.');return}cancelCruise();document.querySelectorAll('button[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range===range)));$('range-note').textContent=range==='LO'?'LOW SPEED · MORE TORQUE':'HIGH RANGE · CRUISING';$('cruise').title=range==='LO'?'Gentle crawl at about 3 mph':'Gentle cruise at about 8 mph';say(range==='LO'?'Rusty: Low range. More grunt. Less hurry. Soft sand still gets a vote.':'Rusty: High range. Back to beach speed.');canvas.focus({preventScroll:true})}
for(const b of document.querySelectorAll('button[data-range]'))b.addEventListener('click',()=>chooseRange(b.dataset.range));
$('recover').addEventListener('click',()=>{if(loaded){reset();setPaused(false)}});
function cancelCruise(){cruise=false;$('cruise').setAttribute('aria-pressed','false');$('cruise').textContent='Cruise'}
$('cruise').addEventListener('click',()=>{cruise=!cruise;$('cruise').setAttribute('aria-pressed',String(cruise));$('cruise').textContent=cruise?'Cruise on':'Cruise';canvas.focus({preventScroll:true})});
// Graphic sunset palette: dark violet overhead, coral horizon, amber dunes and blue surf.
const skyMat=new THREE.MeshBasicNodeMaterial({side:THREE.BackSide,depthWrite:false,fog:false,toneMapped:false});const sy=positionLocal.y.div(1200);skyMat.colorNode=mix(mix(color('#ed8a75'),color('#f2ad79'),smoothstep(-.03,.025,sy)),color('#49355e'),smoothstep(.015,.30,sy));const sky=new THREE.Mesh(new THREE.SphereGeometry(1200,32,20),skyMat);scene.add(sky);scene.fog=new THREE.Fog('#d59388',180,520);
const sun=new THREE.Mesh(new THREE.SphereGeometry(25,40,24),new THREE.MeshBasicMaterial({color:'#ffe3a0',fog:false}));scene.add(sun);
scene.add(new THREE.HemisphereLight('#a498ca','#855063',1.7));const light=new THREE.DirectionalLight('#ffd39d',2.1);light.castShadow=true;light.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(light.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:1,far:220});light.shadow.bias=-.0002;light.shadow.normalBias=.035;scene.add(light,light.target);
function geoGrid(nx,nz,fn){const p=[],idx=[];for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){p.push(...fn(i/nx,j/nz));if(i<nx&&j<nz){let k=j*(nx+1)+i;idx.push(k,k+nx+1,k+1,k+1,k+nx+1,k+nx+2)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();return g}
const waterGeo=geoGrid(80,180,(u,v)=>[-800+u*800,-.18,-600+v*1200]);const water=new THREE.Mesh(waterGeo,new THREE.MeshBasicMaterial({color:0xffffff,vertexColors:true,toneMapped:false}));waterGeo.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(waterGeo.attributes.position.count*3),3));scene.add(water);const seaDark=new THREE.Color('#386879'),seaLight=new THREE.Color('#659699'),seaColor=new THREE.Color();
const foams=[];for(let l=0;l<4;l++){const g=geoGrid(1,300,(u,v)=>[u,0,v]),mat=new THREE.MeshBasicMaterial({color:l%2?'#facb97':'#ffe3b8',transparent:true,opacity:.7,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.Mesh(g,mat);mesh.frustumCulled=false;scene.add(mesh);foams.push({g,mat,l})}
function waterUpdate(p,t){const center=Math.floor(p.z/32)*32,origin=physics.origin;const a=waterGeo.attributes.position;for(let j=0;j<=180;j++){const z=center-600+j*1200/180,coast=shore(z);for(let i=0;i<=80;i++){const d=-780+i*780/80,k=j*81+i,breakWave=Math.sin(d*.22+t*1.05+Math.sin(z*.033)*.35);const band=Math.floor((breakWave+1)*3)/6;seaColor.lerpColors(seaDark,seaLight,band);waterGeo.attributes.color.setXYZ(k,seaColor.r,seaColor.g,seaColor.b);a.setXYZ(k,coast+d-origin.x,-.19+(breakWave*.35+Math.sin(d*.072-t*.5+z*.015)*.2)*smooth(-1,-18,d),z-origin.z)}}a.needsUpdate=true;waterGeo.attributes.color.needsUpdate=true;if(frameCount%6===0)waterGeo.computeVertexNormals();waterGeo.computeBoundingSphere();for(const f of foams){const ar=f.g.attributes.position,phase=(t*.11+f.l/4)%1,run=Math.sin(phase*Math.PI);f.mat.opacity=.55*Math.sin(phase*Math.PI);for(let j=0;j<=300;j++){const z=center-420+j*2.8,coast=shore(z),front=coast-10+run*18+Math.sin(z*.14-t*.55)*.45;for(let i=0;i<2;i++){const x=front-i*(.22+(1-run)*2);ar.setXYZ(j*2+i,x-origin.x,Math.max(-.15,baseHeight(x,z))+.028,z-origin.z)}}ar.needsUpdate=true}}
// Recent tread prints add fine detail on top of the physically displaced terrain.
const trackMax=7000,trackMesh=new THREE.InstancedMesh(new THREE.PlaneGeometry(.32,.18),new THREE.MeshBasicMaterial({color:'#815360',transparent:true,opacity:.31,depthWrite:false,side:THREE.DoubleSide}),trackMax);trackMesh.count=0;trackMesh.frustumCulled=false;scene.add(trackMesh);let trackCount=0;
function printAt(p,heading){const ox=physics.origin.x,oz=physics.origin.z,h=field.height(p.x,p.z);const slopeX=(field.height(p.x+.2,p.z)-field.height(p.x-.2,p.z))/.4,slopeZ=(field.height(p.x,p.z+.2)-field.height(p.x,p.z-.2))/.4;dummy.position.set(p.x-ox,h+.018,p.z-oz);dummy.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),new THREE.Vector3(-slopeX,1,-slopeZ).normalize());dummy.rotateZ(heading);dummy.scale.set(1,1,1);dummy.updateMatrix();trackMesh.setMatrixAt(trackCount++%trackMax,dummy.matrix);trackMesh.count=Math.min(trackCount,trackMax);trackMesh.instanceMatrix.needsUpdate=true}
// Bounded ballistic sand spray; tyre slip drives emission even when the chassis is stopped.
const sandParticles=Array.from({length:420},()=>({life:0,x:0,y:0,z:0,vx:0,vy:0,vz:0,size:1}));let sandCursor=0,sprayCount=0;
const spray=new THREE.InstancedMesh(new THREE.OctahedronGeometry(.045,0),new THREE.MeshStandardMaterial({color:'#efb17a',roughness:1}),sandParticles.length);spray.frustumCulled=false;scene.add(spray);
function kickSand(mark,heading){if(mark.soft<.18||mark.slip<.45)return;const count=Math.min(10,Math.ceil(mark.slip*mark.soft*2.4)),fx=-Math.sin(heading),fz=-Math.cos(heading);for(let j=0;j<count;j++){const a=sandParticles[sandCursor++%sandParticles.length],throwSpeed=1.4+Math.min(6,mark.slip)*(.5+Math.random()*.4),side=(Math.random()-.5)*1.8;a.life=.65+Math.random()*.4;a.x=mark.x+(Math.random()-.5)*.22;a.z=mark.z+(Math.random()-.5)*.22;a.y=field.height(a.x,a.z)+.14;a.vx=-fx*throwSpeed*mark.dir+Math.cos(heading)*side;a.vz=-fz*throwSpeed*mark.dir-Math.sin(heading)*side;a.vy=1.1+Math.random()*1.8+mark.slip*.11;a.size=.5+Math.random()*1.2;sprayCount++}}
function updateSpray(dt){for(let i=0;i<sandParticles.length;i++){const a=sandParticles[i];if(a.life>0){a.life-=dt;a.vy-=7.8*dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.z+=a.vz*dt;if(a.y<field.height(a.x,a.z))a.life=0}dummy.position.set(a.x-physics.origin.x,a.y,a.z-physics.origin.z);dummy.rotation.set(a.life*5,i,0);dummy.scale.setScalar(a.life>0?a.size*Math.min(1,a.life*5):0);dummy.updateMatrix();spray.setMatrixAt(i,dummy.matrix)}spray.instanceMatrix.needsUpdate=true}

// Low-poly grasses and distant driftwood repeat by world region, not along a fixed map edge.
const flagMat=new THREE.MeshBasicMaterial({color:'#ef8259',side:THREE.DoubleSide});const props=new THREE.Group();scene.add(props);const grassMat=new THREE.MeshStandardMaterial({color:'#77506a',side:THREE.DoubleSide,roughness:1});const grass=new THREE.InstancedMesh(new THREE.ConeGeometry(.14,.9,3),grassMat,650);scene.add(grass);let propCenter='';const propMat=new THREE.MeshStandardMaterial({color:'#65445b',roughness:1});
function refreshProps(p){const region=Math.floor(p.z/128),rx=Math.floor(p.x/128),key=`${rx},${region}`;if(key===propCenter)return;propCenter=key;for(const o of [...props.children]){props.remove(o);o.geometry.dispose()}stops=[];for(let r=region-1;r<=region+1;r++){const z=r*128-36,x=shore(z)+48+18*Math.sin(r*2.3);stops.push({x,z,id:r});const post=new THREE.Mesh(new THREE.CylinderGeometry(.065,.07,2.1,5),propMat);post.position.set(x-physics.origin.x,field.height(x,z)+1.05,z-physics.origin.z);props.add(post);const flag=new THREE.Mesh(new THREE.PlaneGeometry(.85,.42),flagMat);flag.position.copy(post.position).add(new THREE.Vector3(.4,.72,0));props.add(flag)}for(let i=0;i<650;i++){const u=Math.sin(i*132.17+rx*13.2+region*41.4)*43758.5453,v=Math.sin(i*33.75+region*31.8)*19453.41,z=region*128-190+(v-Math.floor(v))*500,x=shore(z)+50+(u-Math.floor(u))*220;if(Math.abs(x-p.x)>240){dummy.scale.setScalar(0)}else dummy.scale.set(.7,.4+(i%7)*.13,.7);dummy.position.set(x-physics.origin.x,baseHeight(x,z)+.3,z-physics.origin.z);dummy.rotation.set(0,i*2.7,.1);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix)}grass.instanceMatrix.needsUpdate=true;grass.computeBoundingSphere()}
function mergeRigid(group){group.updateWorldMatrix(true,true);const inv=group.matrixWorld.clone().invert(),sets=new Map(),remove=[];group.traverse(o=>{if(!o.isMesh)return;let g=o.geometry.clone();g=g.index?g.toNonIndexed():g;for(const name of Object.keys(g.attributes))if(!['position','normal'].includes(name))g.deleteAttribute(name);g.applyMatrix4(inv.clone().multiply(o.matrixWorld));const key=o.material.uuid;if(!sets.has(key))sets.set(key,{mat:o.material,geos:[]});sets.get(key).geos.push(g);remove.push(o)});for(const o of remove)o.removeFromParent();for(const v of sets.values()){const mesh=new THREE.Mesh(mergeGeometries(v.geos),v.mat);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh)}}
function reset(announce=true){cancelCruise();const current=physics.position(),z=loaded?current.z:0,x=shore(z)+(previewMode?18:30);terrain.update(x,z);physics.reset(x,z,field.height(x,z));keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);lastStamp=[];camYaw=0;camera.position.set(x-physics.origin.x+7,field.height(x,z)+4,z-physics.origin.z+11);if(announce)say('Rusty: Back on four wheels. We saw nothing.');}
function maybeRebase(){const p=physics.rb.translation();if(Math.abs(p.x)<512&&Math.abs(p.z)<512)return;const x=Math.round(p.x/32)*32,z=Math.round(p.z/32)*32;physics.rebase(x,z);camera.position.x-=x;camera.position.z-=z;terrain.rebase();trackCount=trackMesh.count=0;propCenter='';}
function sync(dt){const p=physics.position(),local=physics.rb.translation(),rot=physics.rb.rotation();q.set(rot.x,rot.y,rot.z,rot.w);truck.position.set(local.x,local.y,local.z);truck.quaternion.copy(q);truck.translateY(-.70);const f=physics.forward(),heading=Math.atan2(-f.x,-f.z);wheels.forEach((w,i)=>{const length=physics.vehicle.wheelSuspensionLength(i)??.38;w.susp.position.y=.70+.06-length;w.steer.rotation.y=wheelLayout[i].front?physics.steer:0;w.roll.rotation.x=-physics.tyres[i].angle;});
 for(const mark of physics.marks.splice(0)){printAt(mark,heading);kickSand(mark,heading)}

 let delta=Math.atan2(Math.sin(heading-camYaw),Math.cos(heading-camYaw));camYaw+=delta*(1-Math.exp(-dt*2));const narrow=innerWidth<700,dist=previewMode?9.5:narrow?13.5:10.5,lateral=previewMode?2:narrow?.5:3.7;temp.set(local.x+Math.sin(camYaw)*dist+Math.cos(camYaw)*lateral,local.y+(previewMode?2.8:narrow?4.1:3.3),local.z+Math.cos(camYaw)*dist-Math.sin(camYaw)*lateral);temp.y=Math.max(temp.y,field.height(temp.x+physics.origin.x,temp.z+physics.origin.z)+2);camera.position.lerp(temp,1-Math.exp(-dt*(reduced?12:4)));camera.lookAt(local.x+f.x*(previewMode?1:3),local.y+1,local.z+f.z*(previewMode?1:3));sky.position.copy(camera.position);sun.position.copy(camera.position).add(new THREE.Vector3(-430,105,-650));light.position.set(local.x-60,local.y+75,local.z-65);light.target.position.set(local.x,local.y,local.z);
 $('game').classList.toggle('driving',physics.travel>8);$('speed').textContent=Math.round(Math.abs(physics.speed)*2.237);const d=p.x-shore(p.z),maxSlip=Math.max(...physics.tyres.map(w=>w.slip)),contacts=[0,1,2,3].filter(i=>physics.vehicle.wheelIsInContact(i)).length;$('surface').textContent=physics.stuck?'BOGGED · EASE OFF':contacts===0?'AIRBORNE':d<6?'SHALLOWS':maxSlip>1.2&&Math.abs(physics.speed)<1?'WHEELSPIN':physics.range==='LO'?'4LO · LOW RANGE':d>43?'4HI · SOFT SAND':'4HI · FIRM SAND';Object.assign(canvas.dataset,{renderer:renderer.backend.isWebGPUBackend?'webgpu':'webgl2',speed:physics.speed.toFixed(2),distance:physics.travel.toFixed(1),ruts:String(field.stamps),depth:field.deepest.toFixed(3),contacts:String(contacts),worldZ:p.z.toFixed(1),fps:String(Math.round(1/Math.max(.001,dt))),height:p.y.toFixed(2),tiles:String(terrain.tiles.size),physics:'rapier-rigid-body',range:physics.range,slip:maxSlip.toFixed(2),wheelRpm:(Math.max(...physics.tyres.map(w=>Math.abs(w.omega)))*60/(Math.PI*2)).toFixed(1),stuck:String(physics.stuck),spray:String(sprayCount)});
 if(physics.stuck&&elapsed>quipUntil)say('Rusty: Congratulations. You’ve excavated a parking space. Ease off, try reversing—or use Recover.');
 for(const s of stops)if(!stopSet.has(s.id)&&Math.hypot(p.x-s.x,p.z-s.z)<10){stopSet.add(s.id);$('mission').textContent=`${stopSet.size} beach stops found. The coast keeps going.`;say('Rusty: Another sunset stop. Still no errands.')}if(d<4&&elapsed>quipUntil)say('Rusty: Four-wheel drive. Not a submarine.');const up=new THREE.Vector3(0,1,0).applyQuaternion(q);if(up.y<.25&&elapsed>quipUntil)say('Rusty: Excellent view of the tyres. Press R to recover.');refreshProps(p);return p;
}
function mapDraw(p){const c=$('map').getContext('2d');c.clearRect(0,0,160,180);c.fillStyle='#6c5476';c.fillRect(0,0,160,180);c.fillStyle='#366975';c.beginPath();c.moveTo(0,0);for(let i=0;i<=180;i+=5){const z=p.z+(i-90)*1.4,x=80+(shore(z)-p.x)*.9;c.lineTo(x,i)}c.lineTo(0,180);c.fill();for(const s of stops){const x=80+(s.x-p.x)*.9,y=90+(s.z-p.z)/1.4;c.fillStyle=stopSet.has(s.id)?'#ffe1a0':'#ef9975';c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill()}c.save();c.translate(80,90);c.rotate(-camYaw);c.fillStyle='#fff0c8';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,5);c.lineTo(4,5);c.fill();c.restore()}
function setPaused(value){if(!loaded)return;if(previewMode){paused=value;canvas.dataset.previewPaused=String(value);last=performance.now();accumulator=0;return}paused=value;soundtrack.pause(value);if(value)cancelCruise();$('paused').hidden=!value;keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));last=performance.now();accumulator=0;if(!value)canvas.focus({preventScroll:true});if(audio)audio.master.gain.setTargetAtTime(value||!audio.on?0:.09,audio.ctx.currentTime,.1)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer?.setSize(innerWidth,innerHeight)}
function exit(){if(parent!==window)parent.postMessage({type:'lc100:drive-close'},location.origin);else location.href='../#test-drive'}
$('exit').addEventListener('click',exit);$('pause').addEventListener('click',()=>setPaused(true));$('resume').addEventListener('click',()=>setPaused(false));$('reset').addEventListener('click',()=>{reset();setPaused(false)});
addEventListener('keydown',e=>{if(previewMode)return;if(e.code==='Escape'){e.preventDefault();setPaused(!paused);return}if(e.code==='KeyL'){e.preventDefault();if(loaded)chooseRange(physics.range==='HI'?'LO':'HI');return}if(e.code==='KeyR'){if(loaded)reset();return}if(['Space','KeyS','ArrowDown'].includes(e.code))cancelCruise();if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&!['BUTTON','INPUT'].includes(e.target.tagName)){e.preventDefault();keys.add(e.code)}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(loaded&&!previewMode)setPaused(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});addEventListener('resize',resize);
for(const button of document.querySelectorAll('[data-control]')){const key=button.dataset.control;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);touch[key]=true;button.classList.add('pressed')});for(const ev of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(ev,()=>{touch[key]=false;button.classList.remove('pressed')})}
$('sound').addEventListener('click',async()=>{try{if(!audio){const ctx=new AudioContext(),master=ctx.createGain(),engine=ctx.createOscillator(),filter=ctx.createBiquadFilter();master.gain.value=.09;master.connect(ctx.destination);engine.type='sawtooth';filter.type='lowpass';filter.frequency.value=160;engine.connect(filter);const eg=ctx.createGain();eg.gain.value=.35;filter.connect(eg);eg.connect(master);engine.start();const b=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*.1;const surf=ctx.createBufferSource();surf.buffer=b;surf.loop=true;surf.connect(master);surf.start();audio={ctx,master,engine,on:true}}else audio.on=!audio.on;await audio.ctx.resume();audio.master.gain.setTargetAtTime(audio.on&&!paused?.09:0,audio.ctx.currentTime,.15);$('sound').textContent=audio.on?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(audio.on));canvas.focus()}catch{$('sound').textContent='Sound unavailable'}});
async function init(){try{
 renderer=new THREE.WebGPURenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,previewMode?1:mobile?1.2:1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;await renderer.init();physics=await DrivePhysics.create(field);terrain=new TerrainView(scene,physics,field);$('load-status').textContent='Shaping dunes. Reconsidering the driveway.';
 const ec=document.createElement('canvas');ec.width=512;ec.height=256;const ex=ec.getContext('2d'),eg=ex.createLinearGradient(0,0,0,256);eg.addColorStop(0,'#574b7e');eg.addColorStop(.42,'#ce96a7');eg.addColorStop(.5,'#ffd19a');eg.addColorStop(.57,'#c37c65');eg.addColorStop(1,'#63475d');ex.fillStyle=eg;ex.fillRect(0,0,512,256);const et=new THREE.CanvasTexture(ec);et.mapping=THREE.EquirectangularReflectionMapping;et.colorSpace=THREE.SRGBColorSpace;const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(et).texture;scene.environmentIntensity=.6;pmrem.dispose();et.dispose();
 const gltf=await new GLTFLoader().loadAsync('lc100.glb?v=traction-3');truck=gltf.scene;scene.add(truck);for(const w of wheelLayout){const susp=truck.getObjectByName('Susp_'+w.name),st=truck.getObjectByName('Steer_'+w.name),roll=truck.getObjectByName('Roll_'+w.name);wheels.push({susp,steer:st,roll});mergeRigid(roll)}mergeRigid(truck.getObjectByName('Body'));reset(false);for(let i=0;i<240;i++)physics.step(1/120,{turn:0});sync(1);waterUpdate(physics.position(),0);mapDraw(physics.position());await renderer.compileAsync(scene,camera);loaded=true;$('loading').hidden=true;if(previewMode){paused=!previewActive;renderer.render(scene,camera);parent.postMessage({type:'lc100:preview-ready'},location.origin)}else canvas.focus();last=performance.now();renderer.setAnimationLoop(frame);
 }catch(e){console.error('Beach drive initialization failed',e);$('load-status').textContent='This browser couldn’t start the 3D drive. Try a recent browser with graphics acceleration enabled.';document.querySelector('.loadline').hidden=true;const b=document.createElement('button');b.className='primary';b.textContent='Back to the truck';b.addEventListener('click',exit);$('loading').append(b)}}
function frame(now){if(dead)return;const dt=Math.min(.06,(now-last)/1000);last=now;if(paused)return;elapsed+=dt;frameCount++;const input={gas:keys.has('KeyW')||keys.has('ArrowUp')||touch.gas,reverse:keys.has('KeyS')||keys.has('ArrowDown')||touch.brake,brake:keys.has('Space'),turn:(keys.has('KeyA')||keys.has('ArrowLeft')||touch.left?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')||touch.right?1:0),cruise};if(input.reverse||input.brake){cancelCruise();input.cruise=false}const p=physics.position();if(previewMode){const f=physics.forward(),heading=Math.atan2(-f.x,-f.z),desired=Math.atan2(-(shore(p.z-15)+18-p.x),15),error=Math.atan2(Math.sin(desired-heading),Math.cos(desired-heading));input.turn=clamp(error*2.4,-1,1);input.cruise=true;}terrain.update(p.x,p.z);accumulator+=dt;let steps=0;while(accumulator>=1/120&&steps++<8){physics.step(1/120,input);accumulator-=1/120}maybeRebase();const pos=sync(dt);if(frameCount%8===0)terrain.refresh();waterUpdate(pos,elapsed);if(frameCount%5===0)mapDraw(pos);updateSpray(dt);if(audio)audio.engine.frequency.setTargetAtTime(26+Math.max(...physics.tyres.map(w=>Math.abs(w.omega)))*(physics.range==='LO'?2.8:1.4),audio.ctx.currentTime,.15);renderer.render(scene,camera)}
addEventListener('message',event=>{if(!previewMode||event.source!==parent||event.origin!==location.origin||event.data?.type!=='lc100:preview-active')return;previewActive=event.data.active===true&&!document.hidden;setPaused(!previewActive)});
addEventListener('pagehide',()=>{dead=true;soundtrack.dispose();renderer?.setAnimationLoop(null);physics?.dispose();renderer?.dispose();audio?.ctx.close()},{once:true});init();
